[config]
schemaVerison = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "quasikyo"
name = "RumbleRain"
description = "Vibrates BPio-capable devices in response to in-game damage events."
websiteUrl = "https://github.com/quasikyo/ror2-mods/tree/main/RumbleRain"
containsNsfwContent = true

[package.dependencies]
bbepis-BepInExPack = "5.4.2121"
tristanmcpherson-R2API = "5.0.5"
Rune580-Risk_Of_Options = "2.8.4"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/RumbleRain.dll"
target = "plugins/RumbleRain/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/RumbleRain.pdb"
target = "plugins/RumbleRain/"

[[build.copy]]
source = "Buttplug.dll"
target = "plugins/RumbleRain/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = ["riskofrain2"]

[publish.categories]
riskofrain2 = ["mods", "nsfw", "client-side"]
