[config]
schemaVerison = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "quasikyo"
name = "LaserScopeCritChance"
description = "Mod that makes the red item Laser Scope give a 5% crit chance bonus similar to Predatory Instincts, Harvester's Scythe, and Shatterspleen."
websiteUrl = "https://github.com/quasikyo/ror2-mods/tree/main/LaserScopeCritChance"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2121"
tristanmcpherson-R2API = "5.0.5"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/LaserScopeCritChance.dll"
target = "plugins/LaserScopeCritChance/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/LaserScopeCritChance.pdb"
target = "plugins/LaserScopeCritChance/"

[[build.copy]]
source = "../LaserScopeCritChance.language"
target = "plugins/LaserScopeCritChance/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = ["riskofrain2"]

[publish.categories]
riskofrain2 = ["mods", "client-side", "server-side"]
