[config]
schemaVerison = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "quasikyo"
name = "ThunderRain"
description = "Shocks PiShocks in response to in-game damage events."
websiteUrl = "https://github.com/quasikyo/ror2-mods/tree/main/ThunderRain"
containsNsfwContent = false
versionNumber = "1.1.1"

[package.dependencies]
bbepis-BepInExPack = "5.4.2121"
tristanmcpherson-R2API = "5.0.5"
Rune580-Risk_Of_Options = "2.8.4"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ThunderRain.dll"
target = "plugins/ThunderRain/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ThunderRain.pdb"
target = "plugins/ThunderRain/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = ["riskofrain2"]

[publish.categories]
riskofrain2 = ["mods", "client-side"]
