[config]
schemaVerison = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "quasikyo"
name = "ReduceRecycler"
description = "Sets Recycler cooldown to instant and adds the cooldown to the run timer. Configurable to only activate after TP event."
websiteUrl = "https://github.com/quasikyo/ror2-mods/tree/main/ReduceRecycler"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2121"
RiskofThunder-R2API_Core = "5.2.0"
Rune580-Risk_Of_Options = "2.8.4"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ReduceRecycler.dll"
target = "plugins/ReduceRecycler/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ReduceRecycler.pdb"
target = "plugins/ReduceRecycler/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = ["riskofrain2"]

[publish.categories]
riskofrain2 = ["mods", "server-side"]
